### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'msi-perkeyrgb==2.1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Linux-Fan** [Askannz/msi-perkeyrgb#25]
My system is a 64-bit Arch Linux

`Linux titanlinux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux`

I installed msi-perkeyrgb from AUR but for some time I cannot run it, although it was working previously. I have all the necessary requirements installed.

```
$ sudo msi-perkeyrgb -c /home/zbyszek/Desktop/Arch\ Linux/Konfiguracja\ Arch\ Linux/Po\ instalacji/MSIKeyboardconfig 
Traceback (most recent call last):
  File "/usr/bin/msi-perkeyrgb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msi-perkeyrgb==2.1' distribution was not found and is required by the application
```

**Comment by Askannz** [comment]
Yeah the Python 3.8 update on Arch broke stuff. The solution is to rebuild the package from scratch. If you use a AUR helper like yay, make sure to do a cleanbuild.

I'll just bump the $pkgrel so that AUR helpers pick up the update and trigger a rebuild.

**Comment by Linux-Fan** [comment]
It works again, thanks!
