### ISSUE TITLE
The 'msi-perkeyrgb==2.1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Linux-Fan** [Askannz/msi-perkeyrgb#38]
This is what I got today when trying to launch msi-perkeyrbg

`$` msi-perkeyrgb -c /home/zbyszek/Dokumenty/Arch\ Linux/Konfiguracja\ Arch\ Linux/Po\ instalacji/MSIKeyboardconfig
Traceback (most recent call last):
  File "/usr/bin/msi-perkeyrgb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msi-perkeyrgb==2.1' distribution was not found and is required by the `application`

I'm not a programmer, but it's seems to me a python-related issue.

**Comment by Linux-Fan** [comment]
Rebuilding msi-perkeyrgb worked.
