### ISSUE TITLE
No module named config on Ubuntu 18.04

### ISSUE THREAD

**Issue by otikscypi** [Askannz/msi-perkeyrgb#4]
Hi,

I was able to install the driver, however trying to run it results in error as follows.

```
  File "/usr/local/bin/msi-perkeyrgb", line 11, in <module>
    load_entry_point('msi-perkeyrgb==1.0', 'console_scripts', 'msi-perkeyrgb')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/msi_perkeyrgb-1.0-py2.7.egg/msi_perkeyrgb/msi_perkeyrgb.py", line 5, in <module>
    from msi_perkeyrgb.config import load_config, ConfigError
ImportError: No module named config
```
I've tried installing pip and config package with it help, but it did not help. Maybe, if it is dependency I am missing, you could point me to module (& version) being used? I am a little at lost here.

I had also problem with missing dependencies during installation, with error "No module named setuptools" thrown. I solved it by installing packages python-setuptools and python3-setuptools from the ubuntu repo. Might be something you will want to add to the description.

**Comment by Askannz** [comment]
Try using python 3 instead.

**Comment by otikscypi** [comment]
Thanks, that helped. I am an idiot, you did mentioned Python 3.4 in the requirements.

**Comment by Askannz** [comment]
Added setuptools to the list of requirements (99c16eb70a3a46c620476e8bb12cf79b131dab80)

**Comment by dfredell** [comment]
I'm having this same issue when trying to run in IntelliJ. I'm no python expert. I was looking at https://stackoverflow.com/a/33615230 and it appears that python doesn't like a package or folder to be named the same as a file. Locally I fixed this my renaming msi_perkeyrgb.py to main.py. 

```
/StudioProjects/msi-perkeyrgb/venv/bin/python /StudioProjects/msi-perkeyrgb/msi_perkeyrgb/msi_perkeyrgb.py
Traceback (most recent call last):
  File "/StudioProjects/msi-perkeyrgb/msi_perkeyrgb/msi_perkeyrgb.py", line 5, in <module>
    from msi_perkeyrgb.config import load_config, ConfigError
  File "/StudioProjects/msi-perkeyrgb/msi_perkeyrgb/msi_perkeyrgb.py", line 5, in <module>
    from msi_perkeyrgb.config import load_config, ConfigError
ModuleNotFoundError: No module named 'msi_perkeyrgb.config'; 'msi_perkeyrgb' is not a package

Process finished with exit code 1
```
